### ISSUE TITLE
PK 32 bytes?

### ISSUE THREAD

**Issue by akalmyk** [Domraider/php-eth-raw-tx#26]
Greetings. 
Receiving an error when trying to get raw transaction:

```
PHP Fatal error:  Uncaught Exception: secp256k1_ecdsa_sign(): Parameter 2 should be 32 bytes in /var/www/nac_backend_test/vendor/domraider/php-eth-raw-tx/src/EthereumRawTx/Transaction.php:137
Stack trace:
#0 /var/www/nac_backend_test/vendor/domraider/php-eth-raw-tx/src/EthereumRawTx/Transaction.php(137): secp256k1_ecdsa_sign_recoverable(Resource id #28, '', '', '\xD0\xF6Ed\xD1\xBF\xF9\xF1\xCAv,_\x06\xA1)...')
#1 /var/www/nac_backend_test/vendor/domraider/php-eth-raw-tx/src/EthereumRawTx/Transaction.php(96): EthereumRawTx\Transaction->sign(Object(BitWasp\Buffertools\Buffer))
#2 /var/www/nac_backend_test/cron/ethertest.php(20): EthereumRawTx\Transaction->getRaw(Object(BitWasp\Buffertools\Buffer), Object(BitWasp\Buffertools\Buffer))
#3 {main}
  thrown in /var/www/nac_backend_test/vendor/domraider/php-eth-raw-tx/src/EthereumRawTx/Transaction.php on line 137
```

I'm sure that PK is ok.

**Comment by etienneroudeix** [comment]
Hi @AlexKalmyk , can you make sure test suite is passing in your environment please ?
If so I will need you to provide me an example of non working pk in order I can reproduce the error.

**Comment by dellasorte** [comment]
Same as https://github.com/Domraider/php-eth-raw-tx/issues/35 compatibility issue between latest secp256k1 and extension secpk256k1-php v.0.1.2
